steps:
  # ১. আপনার বর্তমান সার্ভার থেকে একটি নতুন 'ইমেজ' (Snapshot) তৈরি করা
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'images'
      - 'create'
      - 'nabaax-img-${SHORT_SHA}'
      - '--source-disk=nabaax-managed-group-ctxd' 
      - '--source-disk-zone=us-central1-a'
      - '--force'

  # ২. এই ইমেজটি ব্যবহার করে একটি নতুন 'ইন্সট্যান্স টেম্পলেট' তৈরি করা
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-templates'
      - 'create'
      - 'nabaax-template-${SHORT_SHA}'
      - '--source-instance=nabaax-managed-group-ctxd'
      - '--instance-template-region=us-central1'

  # ৩. আপনার ম্যানেজড গ্রুপকে বলা যে এখন থেকে এই নতুন টেম্পলেটটি ব্যবহার করতে হবে
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'start-update'
      - 'nabaax-managed-group'
      - '--version=template=nabaax-template-${SHORT_SHA}'
      - '--zone=us-central1-a'