steps:
  # ১. ইমেজ তৈরি করা (পুরানো ইমেজ ডিলিট করে নতুন করবে)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'images'
      - 'create'
      - 'nabaax-img-dev' # ফিক্সড নাম
      - '--source-disk=nabaax-managed-group-ctxd'
      - '--source-disk-zone=us-central1-a'
      - '--force'

  # ২. ইন্সট্যান্স টেম্পলেট তৈরি (আগেরটি ডিলিট করে নতুন করবে)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-templates delete nabaax-template-dev --quiet || true
        gcloud compute instance-templates create nabaax-template-dev \
          --source-instance=nabaax-managed-group-ctxd \
          --source-instance-zone=us-central1-a \
          --instance-template-region=us-central1

  # ৩. ম্যানেজড গ্রুপ আপডেট করা
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'rolling-action'
      - 'start-update'
      - 'nabaax-managed-group'
      - '--version=template=nabaax-template-dev'
      - '--zone=us-central1-a'

options:
  logging: CLOUD_LOGGING_ONLY